### ISSUE TITLE
Doesn't work on Juno (doesn't print)

### ISSUE THREAD

**Issue by Datseris** [JuliaPhysics/Measurements.jl#12]
```julia
# while in Juno do:
Pkg.add("Measurements") #works
using Measurements #works
a = 5 ± 0.2 # worked the first time I run it but printed nothing
a #freezes juno entirely
```
Then, restart the Julia kernel in juno because it is frozen and do:
```
a = 5 ± 0.2
```
This freezes julia again, completely. Doesn't even allow me to try and print `a`.

This works fine:
```
a = 5 ± 0.2; typeof(a)
Measurements.Measurement{Float64}
```
So yeah pretty much printing breaks the entire thing down.

Maybe this line messes up Juno; `get(io, :compact, false) ` ?

**Comment by giordano** [comment]
Thanks for the report. I don't use Juno, could you please point me to where printing for Juno is documented? Here are all the methods related to printing defined in the package: https://github.com/JuliaPhysics/Measurements.jl/blob/master/src/Measurements.jl#L93-L120

**Comment by Datseris** [comment]
Fixed by #13

**Comment by giordano** [comment]
I installed Atom and Juno, it works for me without problems:

![screenshot_20171113_115912](https://user-images.githubusercontent.com/765740/32722417-19f26f2c-c86a-11e7-9a83-6272265f81ba.png)

**Comment by Datseris** [comment]
Hm that is weird. For me it doesn't work. I am on Windows 10 and Julia 0.6 with latest Atom/Juno.

Have you used any `Pkg.checkout()` on anything? I haven't.

**Comment by giordano** [comment]
> Hm that is weird. For me it doesn't work.

I trust you ;-)

> I am on Windows 10 and Julia 0.6 with latest Atom/Juno.

Debian and Julia 0.6 here, with latest Atom/Juno I guess, just installed.

> Have you used any `Pkg.checkout()` on anything? I haven't.

Well, I'm on master of `Measurements.jl`, but that shouldn't matter, `show` methods haven't been changed for a while.

Is this perhaps an issue on Windows?  This looks to be the only difference between us.  What happens if you redefine
```julia
Base.show(io::IO, measure::Measurement) = print(io, measure.val, " ± ", measure.err)
```
?

**Comment by Datseris** [comment]
Using this suggestion it still freezes. Could it be that somehow `print(io, ...)` in windows and Juno doesn't take more than 2 argumentrs? @pfitzseb do you know why this happens for me?

**Comment by Datseris** [comment]
Works for me as well after the latest update of Atom!

**Comment by giordano** [comment]
Great!

**Comment by pfitzseb** [comment]
Just for reference: https://github.com/JunoLab/atom-julia-client/issues/380
