### ISSUE TITLE
just use a counter for the tag

### ISSUE THREAD

**Issue by stevengj** [JuliaPhysics/Measurements.jl#15]
I noticed [this in the code](https://github.com/JuliaPhysics/Measurements.jl/blob/0970ef9fb2151b86b43b009872c704e9f83462f7/src/Measurements.jl#L38-L41):

> tag: a (hopefully) unique identifier, it is used to identify a specific measurement in the list of derivatives.  This is usually created with `rand`.  NOTE: only independent measurements have a finite tag.  For dependent quantities the tag is NaN.

It seems like it would be much better just to use a counter here.  You can still use a `Float64` value to get NaN semantics for dependent quantities, since `Float64` has exact 53-bit integers (plenty for a counter). Incrementing a counter is several times faster than calling `rand()` and guarantees a unique result.  You can also easily make it thread-safe by having a per-thread counter.

For example:
```
const tag_counters = Float64[1]
function __init__()
    nthr = Base.Threads.nthreads()
    resize!(tag_counters, nthr)[:] = range(1; length=nthr, step=UInt64(maxintfloat(Float64))÷nthr)
end
```
(this code uses `range` with keyword arguments in 0.7; doesn't seem supported in Compat yet?).  And then, in your constructor, replace the `rand()` call (which isn't thread-safe BTW) with
```
tag = @inbounds(tag_counters[Base.threads.threadid()]) += 1
```

**Comment by giordano** [comment]
Thank you so much for the suggestion!  Getting rid of the `rand()` has always been one of my wishes.  I thought about using a counter, but didn't know how to make it thread-safe.  Your solution is very clever.

Note that the last line is a syntax error:
```julia
julia> tag = @inbounds(tag_counters[Base.Threads.threadid()]) += 1
ERROR: syntax: invalid assignment location "begin
    (inbounds true)
    tag_counters[Base.Threads.threadid()]
    (inbounds pop)
end"
```
Moving the `@inbounds` at the beginning of the line should be fine.

I thought I could use the `UInt64` type instead of `Float64` for the tag, but then I wouldn't be able to use `NaN` for dependent quantities.  An option would be to use `UInt64(0)` for dependent quantities, but in the _extremely_ unlikely case the counter overflows an independent quantity may have `UInt64(0)` as tag.

**Comment by stevengj** [comment]
I thought you used NaN for dependent quantities because you wanted NaN comparison semantics or something. 

If you are willing to check for zero tags, you should definitely use UInt64, which will never overflow as a counter of real objects. (Overflow is not just unlikely, it is impossible unless you have a process running for centuries.)

**Comment by stevengj** [comment]
The only thing to be careful of with a counter is serialization/deserialization. You may want to implement custom serialize methods to assign a new tag to a measurement that is deserialized from another process or something, since the counter is process-specific.

**Comment by giordano** [comment]
> I thought you used NaN for dependent quantities because you wanted NaN comparison semantics or something.

No, I just wanted a number that can't be generated by `rand()`.  If I remember correctly, `rand()` generates number in `[0, 1)`, then also 1 would have worked.

> The only thing to be careful of with a counter is serialization/deserialization.

Isn't this potentially a problem also with `rand()`?  Anyway, what I actually compare to see whether two quantities are really the same one is the triplet (value, error, tag).  This should make collisions between numbers deserialized more unlikely.

> You may want to implement custom serialize methods to assign a new tag to a measurement that is deserialized from another process or something, since the counter is process-specific.

Ok, I'll consider this possibility.  Thanks!
