### ISSUE TITLE
Broken `MeasurementsJunoExt.jl`

### ISSUE THREAD

**Issue by johnzl-777** [JuliaPhysics/Measurements.jl#158]
There seems to be a "broken" line (line 32) in `ext/MeasurementsJunoExt.jl` with the following piece of code that seems to be an incomplete one-line function definition:

```julia
Juno.Row(measure.val, Text(" ± "), measure.err)
```

I've seen this cause precompilation failures (although oddly enough I can't replicate the problem when the package is by itself in a standalone environment).

I assume this should be the fix:

```julia
Juno.Row(measure) = 
Juno.Row(measure.val, Text(" ± "), measure.err)
```

**Comment by longemen3000** [comment]
the error seems from before the Juno functionality was moved into an extension:
https://github.com/JuliaPhysics/Measurements.jl/blob/dc99187d5c3add2c8fd1e129ec0fdc563385e3a7/src/show.jl#L98-L115
