### ISSUE TITLE
Wrong values when multiplication with scalar?

### ISSUE THREAD

**Issue by MichielStock** [JuliaPhysics/Measurements.jl#166]
Unless I completely misunderstand how the error propagation is computed, there seems to be something wrong with the decimal points after the values when multiplying with a constant.

```julia
julia> r = 10.0 ± 0.9
10.0 ± 0.9

julia> r^2
100.0 ± 18.0

julia> π * r^2
314.0 ± 57.0

julia> π * r.val^2
314.1592653589793
```
I don't see why the values would be different, as Measurements should only propagate the errors?

**Comment by giordano** [comment]
https://juliaphysics.github.io/Measurements.jl/stable/usage/#Measurements-in-the-REPL
```
julia> Measurements.value(π * r^2), Measurements.uncertainty(π * r^2)
(314.1592653589793, 56.548667764616276)
```

**Comment by MichielStock** [comment]
But it should output `314.2` not `314.0`, no?
