### ISSUE TITLE
one vs oneunit

### ISSUE THREAD

**Issue by stevengj** [JuliaPhysics/Measurements.jl#31]
I would tend to recommend defining
```jl
one(::Type{Measurement{T}}) where T = one(T)
```
so that `one(3.0 ± 0.1)` gives `1.0` while `oneunit(3.0 ± 0.1)` will continue to give `1.0 ± 0.0`.

`one` has to return a multiplicative identity, but does not have to return the same type, unlike `oneunit` which should generally return a value of the same type.  For dimensionful quantities, it strips away the units, and in general it seems useful to return the underlying numeric type.

(For example, in JuliaLang/julia#30917 we need to decide whether a number type is floating-point or not in order to decide whether to use a pivoted algorithm, in which context it is useful if `one` returns the underling number type.)

**Comment by giordano** [comment]
> For dimensionful quantities, it strips away the units, and in general it seems useful to return the underlying numeric type.

I see the point of `one` vs `oneunit` for dimensionful quantities, but I'm not sure how the same argument applies to `Measurement`s.

I tried adding the method you suggested, but then tests fail at L596
https://github.com/JuliaPhysics/Measurements.jl/blob/95087d7dea1936586d449ef6d6e9808074e0eff1/test/runtests.jl#L590-L596
with the following error
```
Linear algebra: Error During Test at /home/mose/.julia/dev/Measurements/test/runtests.jl:596
  Test threw exception
  Expression: #= /home/mose/.julia/dev/Measurements/test/runtests.jl:596 =# @inferred(det(A)) ≈ 612 ± 9.51262319236918
  return type Measurement{Float64} does not match inferred return type Union{Float64, Measurement{Float64}}
  Stacktrace:
   [1] error(::String) at ./error.jl:33
   [2] macro expansion at /home/mose/.julia/dev/Measurements/test/runtests.jl:596 [inlined]
   [3] macro expansion at /build/julia-wJr69F/julia-1.0.3+dfsg/usr/share/julia/stdlib/v1.0/Test/src/Test.jl:1083 [inlined]
   [4] top-level scope at /home/mose/.julia/dev/Measurements/test/runtests.jl:591
Test Summary:  | Pass  Error  Total
Linear algebra |    3      1      4
ERROR: LoadError: Some tests did not pass: 3 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /home/mose/.julia/dev/Measurements/test/runtests.jl:590
ERROR: Package Measurements errored during testing
```
which is probably related to the issue discussed

**Comment by stevengj** [comment]
If `det(A)` is type-unstable when you return `Float64` from `one`, then it is type-unstable for dimensionful types too, and this is a bug in the `det` function.

I think it's separate from the issue I linked, since the returned "units" of `det` should not depend on whether partial pivoting is performed.   Probably an issue should be filed with Julia.

**Comment by stevengj** [comment]
Hmm, no, I guess type-instability for `det` of dimensionful types is unavoidable since the matrix size (which determines the dimensions of the output) is not known at compile time.

**Comment by stevengj** [comment]
The other downside of making `one` a `Float64` is that it makes `prod` type-unstable.

Okay, then it makes sense to me to leave as-is.

**Comment by stevengj** [comment]
I guess the other way to check whether the type is floating point is `float(x) === x`, which still works for `Measurement`.
