### ISSUE TITLE
Option to always use truncated display of Measurements

### ISSUE THREAD

**Issue by karlwessel** [JuliaPhysics/Measurements.jl#40]
Would it be possible to get an option to tell Measurements to always use the truncated display of error values? 

I'm almost never concerned about all of the digits of a Measurement but even when using an IO with compact display like the REPL it still happens often that Measurements are displayed as a whole. Especially in combination with Unitful.jl or in Tuples or arrays.

**Comment by giordano** [comment]
There is already a PR for Unitful.jl to fix the issue when using the two packages together: https://github.com/PainterQubits/Unitful.jl/pull/213

**Comment by karlwessel** [comment]
I did not know of that PR, that will be definitively a huge improvement! 

However there are still cases where the display is not truncated, like in this MWE:
```
julia> using Measurements

julia> a = 10π ± π
31.4 ± 3.1

julia> a, a
(31.41592653589793 ± 3.141592653589793, 31.41592653589793 ± 3.141592653589793)
```

An option to always use truncation would solve this for all cases where one has no control over whether the IO has compact mode set.

Or, if a global option is not possible, is there some way one can easily force Measurements to be displayed truncated?

**Comment by giordano** [comment]
I don't really like global options.  I'm thinking about simply always using truncated display.

**Comment by karlwessel** [comment]
That would also be totally fine (and reasonable) for me. However, in that case an easy method to display the untrunkated version would probably be good.
