### ISSUE TITLE
Suppress warning of require

### ISSUE THREAD

**Issue by shipengcheng1230** [JuliaPhysics/Measurements.jl#49]
Hello, starting a fresh installation: 
```julia
julia> using Measurements

julia> using SpecialFunctions
┌ Warning: Package Measurements does not have SpecialFunctions in its dependencies:
│ - If you have Measurements checked out for development and have
│   added SpecialFunctions as a dependency but haven't updated your primary
│   environment's manifest file, try `Pkg.resolve()`.
│ - Otherwise you may need to report an issue with Measurements
└ Loading SpecialFunctions into Measurements from project dependency, future warnings for Measurements are suppressed.
```

According to the `Require.jl` doc:

> In the @require block, or any included files, you can use or import the package, but note that you must use the syntax using .Gadfly or import .Gadfly, rather than the usual syntax. Otherwise you will get a warning about Gadfly not being in dependencies.

Perhaps we should use `using .SpecialFunctions` in the corresponding file and the same for all `@require` file to suppress this warning.

**Comment by giordano** [comment]
Good catch, thank you so much!  This should be fixed by #50.
