### ISSUE TITLE
New mean function

### ISSUE THREAD

**Issue by adamslc** [JuliaPhysics/Measurements.jl#6]
It might be nice to implement a new mean function that returns a `Measurement` type. This function would be called as `Measurements.mean(a::AbstractArray)`, and you could optionally specify if it should calculate standard deviation or standard error.

Ideally it would interface nicely with [DataFrames.jl](https://github.com/JuliaStats/DataFrames.jl) so that you could call, for example, `aggregate(data, :myColumn, Measurements.mean)`, and it would return an array with Measurement objects.

**Comment by giordano** [comment]
How do you want to calculate the mean?  As an arithmetic mean or a weighted mean with [inverse-variance weighting](https://en.wikipedia.org/wiki/Inverse-variance_weighting)?  In the former case, `mean((a,b,c))` just works, in the latter case, the package provides the [`weightedmean`](https://github.com/giordano/Measurements.jl#weighted-average) function, see also [the example](https://github.com/giordano/Measurements.jl#weightedmean-function)

**Comment by giordano** [comment]
I'm closing this ticket as I don't think we need a new mean function.  Feel free to reopen in case you disagree, but please better explain your proposal.
