### ISSUE TITLE
Wrong results

### ISSUE THREAD

**Issue by s1291** [JuliaPhysics/Measurements.jl#79]
On julia 1.5.2 and Measurements  v2.3.0:

```
using Measurements
x = 5.0 ± 0.2
y = 8.0 ± 0.3
x + y
```
Output:

`13.0 ± 0.36`

**Comment by giordano** [comment]
What's the issue?

**Comment by s1291** [comment]
@giordano : Sorry, I thought the output is self-explanatory. Shouldn't the result be: 
```
13.0 ± 0.5
```
?

**Comment by giordano** [comment]
There are multiple ways to propagate uncertainties and no one is "perfect" in all cases.  You are expecting to simply sum the absolute values of the uncertainties, but this package chose the [linear error propagation theory](https://en.wikipedia.org/wiki/Propagation_of_uncertainty), as explained in [the manual](https://juliaphysics.github.io/Measurements.jl/stable/) and in the [README.md](https://github.com/JuliaPhysics/Measurements.jl/blob/d55b13d9e2d5d352ee7b4d8bf9b5826acd94888c/README.md#introduction) file.  The manual has an [entire page](https://juliaphysics.github.io/Measurements.jl/stable/appendix/#Uncertainty-Propagation-1) which explains the propagation model adopted here.
